"""untranslate.py 的端到端自测。

造一个合成游戏目录，塞进我们的译文/注入产物 + 一个原生语言包 + 一个存档，
跑一遍还原，检查:
  1. 我们的产物被删干净
  2. 原生语言包、存档、游戏目录骨架完好
  3. 备份能把现场一字不差地恢复回来

跑法:
  <venv>/python.exe tests/_selftest_untranslate.py
"""
import importlib.util
import os
import shutil
import subprocess
import sys

KIT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRIPT = os.path.join(KIT_DIR, 'untranslate.py')
BASE = os.path.join(os.environ.get('TEMP', '/tmp'), 'kit_untranslate')
GAME = os.path.join(BASE, 'UntranslateTest')

# 工作区位置由 kit.json 决定(默认在 kit 目录的上一级)，必须与 untranslate.py
# 实际用的解析结果一致，否则备份落到别处而自测找不到
_kspec = importlib.util.spec_from_file_location('kit', os.path.join(KIT_DIR, 'kit.py'))
_kmod = importlib.util.module_from_spec(_kspec)
_kspec.loader.exec_module(_kmod)
WS = os.path.join(_kmod.load_config()['workspace'], 'UntranslateTest')

BANNER = ('###########################################################\n'
          '#  This rpy file is generated by the project:             #\n'
          '#  https://github.com/abse4411/projz_renpy_translation)   #\n'
          '###########################################################\n')
NATIVE = '# game/game/tl/japanese/native.rpy — shipped by the game author\n'

results = []


def check(label, got, want):
    good = got == want
    results.append(good)
    print(f'{"PASS" if good else "FAIL"}  {label}')
    if not good:
        print(f'        got : {got!r}')
        print(f'        want: {want!r}')


def w(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8', newline='') as f:
        f.write(text)


def wb(path, blob):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'wb') as f:
        f.write(blob)


def path(*parts):
    return os.path.join(GAME, *parts)


# ---------------------------------------------------------------- 造现场
shutil.rmtree(BASE, ignore_errors=True)
shutil.rmtree(WS, ignore_errors=True)
for d in ('game', 'lib', 'renpy'):
    os.makedirs(os.path.join(GAME, d))
wb(os.path.join(GAME, 'UntranslateTest.exe'), b'MZ fake')
w(os.path.join(GAME, 'UntranslateTest.py'), 'init python: pass\n')

# 我们的译文（带 banner）+ 同名 .rpyc
OURS = [
    ('game/tl/schinese/common.rpy', 3800),
    ('game/tl/schinese/chapters/chapter7/script/ch7aly.rpy', 2100),
]
for rel, _ in OURS:
    w(path(rel), BANNER + 'translate schinese x:\n    old "a"\n    new "甲"\n')
    wb(path(rel[:-4] + '.rpyc'), b'\x00rpyc-compiled-bytes\x00')

# 原生语言包（无 banner）——必须原样保留
w(path('game/tl/japanese/native.rpy'), NATIVE)
wb(path('game/tl/japanese/native.rpyc'), b'\x00native-compiled\x00')

# 我们的注入文件
w(path('game/projz_injection.rpy'), BANNER + 'init python: pass\n')
wb(path('game/projz_injection.rpyc'), b'\x00inj\x00')
w(path('game/projz_i18n_inject.rpy'), BANNER + 'define projz_font_dir = "projz_fonts/"\n')
wb(path('game/projz_i18n_inject.rpyc'), b'\x00i18n\x00')
wb(path('game/projz_fonts/SourceHanSansLite.ttf'), b'\x00\x01\x00\x00fake-font' * 10)

# 游戏自己的脚本 + 存档 + 运行时缓存
SCREENS = ('screen main_menu():\n'
           '    tag menu\n'
           '    vbox:\n'
           '        textbutton _("Start") action Start()\n'
           '            textbutton _("I18n settings") action Show("projz_i18n_settings")\n'
           '        textbutton _("Load") action ShowMenu("load")\n')
w(path('game/screens.rpy'), SCREENS)
wb(path('game/screens.rpyc'), b'\x00screens-old-rpyc\x00')
w(path('game/script.rpy'), 'label start:\n    "hello"\n')
wb(path('game/saves/auto-1-LT1.save'), b'\x00save-bytes\x00')
wb(path('game/cache/bytecode.rpyb'), b'\x00bc\x00')
wb(path('game/cache/pyanalysis.rpyb'), b'\x00pa\x00')
wb(path('game/cache/screens.rpyb'), b'\x00sc\x00')
wb(path('game/cache/shaders.txt'), b'shader stuff\n')

# 快照：还原后应当一字不差的东西
KEEP = {}
for rel in ('game/tl/japanese/native.rpy', 'game/tl/japanese/native.rpyc',
            'game/script.rpy', 'game/saves/auto-1-LT1.save',
            'game/cache/shaders.txt', 'UntranslateTest.py'):
    with open(path(rel), 'rb') as f:
        KEEP[rel] = f.read()


def run(*args):
    env = dict(os.environ, PYTHONIOENCODING='utf-8', PYTHONUTF8='1')
    p = subprocess.run([sys.executable, SCRIPT, *args], capture_output=True,
                       env=env, text=True, encoding='utf-8', errors='replace')
    return p.returncode, p.stdout + p.stderr


# ---------------------------------------------------------------- 1) 预览不动任何东西
rc, out = run(GAME, '-n')
check('预览模式返回 0', rc, 0)
check('预览没删译文', os.path.isfile(path('game/tl/schinese/common.rpy')), True)
check('预览没删注入文件', os.path.isfile(path('game/projz_injection.rpy')), True)
check('预览说没改动', '什么都没有改动' in out, True)
check('预览识别出译文', 'game\\tl\\schinese\\' in out, True)
check('预览列了注入文件', 'projz_i18n_inject.rpy' in out, True)
check('预览没把注入文件列为待自查', out.count('projz_i18n_inject.rpy'), 1)
check('预览指出原生语言包不动', 'japanese' in out, True)
check('预览点出 screens.rpy 行号', 'screens.rpy 第 5 行' in out, True)

# ---------------------------------------------------------------- 2) 执行还原
rc, out = run(GAME, '-y')
check('执行返回 0', rc, 0)

check('我们的译文已删除', os.path.exists(path('game/tl/schinese')), False)
check('注入文件已删除', os.path.exists(path('game/projz_injection.rpy')), False)
check('注入 .rpyc 已删除', os.path.exists(path('game/projz_injection.rpyc')), False)
check('i18n 注入已删除', os.path.exists(path('game/projz_i18n_inject.rpy')), False)
check('字体目录已删除', os.path.exists(path('game/projz_fonts')), False)
check('旧 screens.rpyc 已删除', os.path.exists(path('game/screens.rpyc')), False)
check('运行时缓存已删除', os.path.exists(path('game/cache/bytecode.rpyb')), False)
check('screens.rpyb 已删除', os.path.exists(path('game/cache/screens.rpyb')), False)

# 原样保留
for rel, blob in KEEP.items():
    ok_exists = os.path.isfile(path(rel))
    got = None
    if ok_exists:
        with open(path(rel), 'rb') as f:
            got = f.read()
    check(f'保留未改: {rel}', got, blob)

# screens.rpy 精确回到原样（= 原文件去掉那一行注入）
SCREENS_CLEAN = ''.join(
    ln for ln in SCREENS.splitlines(True) if 'projz_i18n_settings' not in ln)
with open(path('game/screens.rpy'), encoding='utf-8') as f:
    screens_now = f.read()
check('screens.rpy 恢复成原样', screens_now, SCREENS_CLEAN)
check('screens.rpy 还有 start 按钮', 'textbutton _("Start")' in screens_now, True)
check('screens.rpy 缩进没被破坏',
      '\n        textbutton _("Load")' in screens_now, True)

# 复核没有再报残留
check('复核无残留', '还有残留' in out, False)

# ---------------------------------------------------------------- 3) 备份能恢复现场
backups = os.path.join(WS, '_还原备份')
stamps = sorted(os.listdir(backups)) if os.path.isdir(backups) else []
check('生成了备份目录', len(stamps), 1)

broot = os.path.join(backups, stamps[0]) if stamps else ''
if broot:
    for rel in ('game/tl/schinese/common.rpy',
                'game/tl/schinese/chapters/chapter7/script/ch7aly.rpy',
                'game/tl/schinese/chapters/chapter7/script/ch7aly.rpyc',
                'game/projz_injection.rpy',
                'game/projz_i18n_inject.rpyc',
                'game/projz_fonts/SourceHanSansLite.ttf',
                'game/screens.rpy',
                'game/cache/bytecode.rpyb'):
        check(f'备份里有 {rel}', os.path.isfile(os.path.join(broot, rel)), True)
    check('备份里有注入后的 screens.rpy',
          'projz_i18n_settings' in open(os.path.join(broot, 'game/screens.rpy'),
                                        encoding='utf-8').read(), True)

    # 把备份盖回去 = 恢复汉化
    for root, dirs, files in os.walk(broot):
        if '_tool' in dirs:
            dirs.remove('_tool')
        rel_root = os.path.relpath(root, broot)
        for fn in files:
            dst = os.path.normpath(os.path.join(GAME, rel_root, fn))
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            shutil.copy2(os.path.join(root, fn), dst)
    check('盖回备份后译文回来了', os.path.isfile(path('game/tl/schinese/common.rpy')), True)
    check('盖回备份后 screens.rpy 也回来了',
          'projz_i18n_settings' in open(path('game/screens.rpy'), encoding='utf-8').read(), True)

# ---------------------------------------------------------------- 4) 空目录 / 入口防御
rc, out = run(GAME, '-n')
check('已还原的游戏再跑预览: 返回 0', rc, 0)

rc, out = run(os.path.join(BASE, 'nope-does-not-exist'), '-y')
check('路径不存在时报错退出', rc, 1)

rc, out = run(path('game'), '-y')
check('拖了 game 子目录会被拦下', rc, 1)
check('拦下时提示拖上面一层', 'game' in out and '上面一层' in out, True)

print()
good = sum(1 for r in results if r)
print(f'==== {good}/{len(results)} passed ====')

shutil.rmtree(BASE, ignore_errors=True)
shutil.rmtree(WS, ignore_errors=True)
sys.exit(0 if good == len(results) else 1)
